imports:
    - { resource: tables.yml }

services:
    phpbb.boardrules.admin.controller:
        class: phpbb\boardrules\controller\admin_controller
        arguments:
            - @config
            - @dbal.conn
            - @request
            - @template
            - @user
            - @phpbb.boardrules.operator

    phpbb.boardrules.controller:
        class: phpbb\boardrules\controller\main_controller
        arguments:
            - @config
            - @controller.helper
            - @phpbb.boardrules.operator
            - @template
            - @user
            - %tables.boardrules%

    phpbb.boardrules.entity:
        class: phpbb\boardrules\entity\rule
        scope: prototype # scope MUST be prototype for this to work!
        arguments:
            - @dbal.conn
            - %tables.boardrules%

    phpbb.boardrules.listener:
        class: phpbb\boardrules\event\listener
        arguments:
            - @controller.helper
            - @template
        tags:
            - { name: event.listener }

    phpbb.boardrules.nestedset_rules:
        class: phpbb\boardrules\operators\nestedset_rules
        arguments:
            - @dbal.conn
            - @phpbb.boardrules.table_lock
            - %tables.boardrules%

    phpbb.boardrules.operator:
        class: phpbb\boardrules\operators\rule
        arguments:
            - @service_container
            - @phpbb.boardrules.nestedset_rules
            - %tables.boardrules%

    phpbb.boardrules.table_lock:
        class: phpbb\lock\db
        arguments:
            - boardrules.table_lock.boardrules_table
            - @config
            - @dbal.conn
