imports:
    - { resource: tables.yml }

services:
    phpbb.boardrules.controller:
        class: phpbb\boardrules\controller\main_controller
        arguments:
            - @config
            - @controller.helper
            - @template
            - @user
            - %tables.boardrules%
    phpbb.boardrules.listener:
        class: phpbb\boardrules\event\listener
        arguments:
            - @controller.helper
            - @template
        tags:
            - { name: event.listener }

    phpbb.boardrules.operator:
        class: phpbb\boardrules\operators\rule
        arguments:
            - @dbal.conn
            - @phpbb.boardrules.nestedset_rules
            - %tables.boardrules%

    phpbb.boardrules.nestedset_rules:
        class: phpbb\boardrules\operators\nestedset_rules
        arguments:
            - @dbal.conn
            - @cron.lock_db
            - %tables.boardrules%
